[font]
size = 13.0

[font.normal]
family = "Sarasa Mono K Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -1

[window]
opacity = 0.8

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[env]
TERM = "xterm-256color"

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
# background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"
