# antigen
[ ! -f ~/antigen.zsh ] && curl -L git.io/antigen > ~/antigen.zsh
source ~/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle command-not-found
antigen bundle sudo

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen theme ChesterYue/ohmyzsh-theme-passion

antigen apply

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# tmux over ssh
#if [[ "$TMUX" == "" ]] && [[ "$SSH_CONNECTION" != "" ]]; then
#    WHOAMI=$(whoami)
#    SESSION_NAME="${WHOAMI}-REMOTE"
#    if tmux has-session -t $SESSION_NAME 2>/dev/null; then
#        tmux -2 attach-session -t $SESSION_NAME
#    else
#        tmux -2 new-session -s $SESSION_NAME
#    fi
#fi
