### Zinit Settings {{{

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node
### End of Zinit's installer chunk

## Oh My Zsh Theme Setting
ZSH_THEME="ohmyzsh-theme-passion"
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit cdclear -q
#
setopt promptsubst
autoload colors
colors
# Load Prompt
zinit light ChesterYue/ohmyzsh-theme-passion

# Nodenv
zinit ice from"gitlab"
zinit light riverglide/zsh-nodenv
eval "$(nodenv init -)"

zinit snippet OMZP::command-not-found
zinit snippet OMZP::sudo

# fzf
zinit wait lucid for \
  atload"zicompinit; zicdreplay" Aloxaf/fzf-tab
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

zinit wait lucid for \
 atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    zdharma/fast-syntax-highlighting \
 blockf \
    zsh-users/zsh-completions \
 atload"!_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions

### }}} END Zinit Settings

# for zsh shortcuts
bindkey -e

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt HIST_IGNORE_DUPS
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# Add path
export PATH="$HOME/.local/bin:$PATH"

# Default editor
export EDITOR=nvim

# ls alias
alias ls="ls --color=auto -h"
