# Configuration for Alacritty, the GPU enhanced terminal emulator.

env:
  # TERM variable
  TERM: xterm-256color

window:
  # Window padding (changes require restart)
  padding:
    x: 17
    y: 17

  # Window title
  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 100000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    #family: DejaVuSansMono Nerd Font
    #family: MesloLGS NF
    family: Hack
    style: Regular

  # Bold font face
  bold:
    #family: DejaVuSansMono Nerd Font
    #family: MesloLGS NF
    family: Hack
    style: Bold

  # Italic font face
  italic:
    #family: DejaVuSansMono Nerd Font
    #family: MesloLGS NF
    family: Hack
    style: Italic

  # Bold italic font face
  bold_italic:
    #family: DejaVuSansMono Nerd Font
    #family: MesloLGS NF
    family: Hack
    style: Bold Italic

  # Point size
  size: 8

  offset:
    x: 0
    y: 0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# Colors
colors:
  # Default colors
  primary:
    background: '0x2d2d2d'
    foreground: '0xd3d0c8'

  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  selection:
    text: '0xd3d0c8'
    background: '0x5d5d5d'

  # Normal colors
  #normal:
  #  black:   '0x282a2e'
  #  red:     '0xa54242'
  #  green:   '0x8c9440'
  #  yellow:  '0xde935f'
  #  blue:    '0x5f819d'
  #  magenta: '0x85678f'
  #  cyan:    '0x5e8d87'
  #  white:   '0x707880'

  # Bright colors
  #bright:
  #  black:   '0x373b41'
  #  red:     '0xcc6666'
  #  green:   '0xb5bd68'
  #  yellow:  '0xf0c674'
  #  blue:    '0x81a2be'
  #  magenta: '0xb294bb'
  #  cyan:    '0x8abeb7'
  #  white:   '0xc5c8c6'

  # Normal colors
  normal:
    black:   '0x3D4C5F'
    red:     '0xEE4F84'
    green:   '0x53E2AE'
    yellow:  '0xF1FF52'
    blue:    '0x6498EF'
    magenta: '0x985EFF'
    cyan:    '0x24D1E7'
    white:   '0xE5E5E5'

  # Bright colors
  bright:
    black:   '0x56687E'
    red:     '0xF48FB1'
    green:   '0xA1EFD3'
    yellow:  '0xF1FA8C'
    blue:    '0x92B6F4'
    magenta: '0xBD99FF'
    cyan:    '0x87DFEB'
    white:   '0xF8F8F2'

background_opacity: 0.85

key_bindings:
    # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  - { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }
  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }
